

INSERT INTO USERS (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL) VALUES (1, 'admin', '$2a$04$pnc4sJXTKKy9.FYhU4cJzugeRs0P/r0X8uKH2950ZVjhdr.OCk6KG', 'admin', 'admin', 'admin@admin.com');
INSERT INTO USERS (ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL) VALUES (2, 'user', '$2a$04$SYeqFCPBywqjQ0tMnle6XuMzxCVlyrap3c/IEA.34snhmAqWcaKpW', 'USER', 'USER', 'enabled@USER.com');

INSERT INTO AUTHORITIES (ID, name) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITIES (ID, name) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (ID, USER_ID, AUTHORITY_ID) VALUES (1,1, 1);
INSERT INTO USER_AUTHORITY (ID, USER_ID, AUTHORITY_ID) VALUES (2,1, 2);
INSERT INTO USER_AUTHORITY (ID, USER_ID, AUTHORITY_ID) VALUES (3,2, 1);