
--DROP TABLE users IF EXISTS;
--DROP TABLE authorities IF EXISTS;
--DROP TABLE user_authority

CREATE TABLE USER (
  ID         INTEGER PRIMARY KEY,
  USERNAME VARCHAR(30),
  EMAIL  VARCHAR(50),
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  PASSWORD VARCHAR(255),
  ENABLED BOOLEAN,
  LAST_PASSWORD_RESET_DATE DATE
);


CREATE TABLE QUESTION (
  ID         INTEGER AUTO_INCREMENT PRIMARY KEY,
  USER_ID INTEGER NOT NULL,
  TITLE VARCHAR(30),
  QUESTION_BODY  VARCHAR(255)
);


CREATE TABLE AUTHORITY (
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR(50)

);


CREATE TABLE USER_AUTHORITY (
	ID         INTEGER PRIMARY KEY,
	USER_ID INTEGER,
	AUTHORITY_ID INTEGER

);


