
--DROP TABLE users IF EXISTS;
--DROP TABLE authorities IF EXISTS;
--DROP TABLE user_authority

CREATE TABLE USERS (
  ID         INTEGER PRIMARY KEY,
  USERNAME VARCHAR(30),
  EMAIL  VARCHAR(50),
  FIRST_NAME VARCHAR(50),
  LAST_NAME VARCHAR(50),
  PASSWORD VARCHAR(255)
);


CREATE TABLE AUTHORITIES (
	ID INTEGER PRIMARY KEY,
	NAME VARCHAR(50)

);


CREATE TABLE USER_AUTHORITY (
	ID         INTEGER PRIMARY KEY,
	USER_ID INTEGER,
	AUTHORITY_ID INTEGER

);


