# config context path to "/" by setting an empty string
#server:
#  contextPath:
server:
  port: 8080

# JACKSON
spring:
  profiles: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true    
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;
    username: sa
    password: 
    driverClassName: org.h2.Driver
   # schema: schema.sql
   # data: data.sql
  jpa:
    hibernate:
      # possible values: validate | update | create | create-drop
      ddl-auto: none
      dialect: org.hibernate.dialect.H2Dialect 
  h2:
    console:
      enabled: true
      path: /h2
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: /auth
      refresh: /refresh

#logging:
#  level:
#    org.springframework:
#      security: DEBUG